import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "./_components/navbar/Navbar";
import ThemeProvider from "@/theme-provider";
import Footer from "./_components/footer/Footer";

import About from "./about/page";
import Skills from "./skills/page";
import Projects from "./projects/page";
import Contact from "./contact/page";
import Home from "./home/page";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white dark:bg-[#1a1a2e]`}
      >
        <ThemeProvider>
          <div className="min-h-screen flex flex-col">
             <Navbar />
            <main className=" flex-1">
                {/* {children} */}

                <Home/>
                   <About/>  
                   <Skills/>  
                <Projects/>
                <Contact/>  
            </main>
          
            <Footer />
          </div>

        </ThemeProvider>

      </body>
    </html>
  );
}
